name: .NET Core

on: push

jobs:
  build:

    runs-on: windows-latest
    # container: mcr.microsoft.com/dotnet/core/sdk:5.0

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0
    - run: dotnet --version
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
