name: .NET Core

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:5.0

    steps:
    - uses: actions/checkout@v2
    - run: dotnet --version
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
